Traceback (most recent call last):
  File "/home/mc5635/yahtzee/yahtzee_rl/train_gpu.py", line 321, in <module>
    dqn, target_dqn = train_dqn(make_env,
  File "/home/mc5635/yahtzee/yahtzee_rl/train_gpu.py", line 256, in train_dqn
    category = list(env.categories.keys())[cat_idx]
IndexError: list index out of range
